
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/product/v1/items/{itemNumber}": {
    /**
     * Get product details by item number
     * @description Retrieve detailed information about a specific product.
     */
    get: operations["getProductByItemNumber"];
  };
  "/stock/v2/locations/{locationId}/items/{itemNumber}": {
    /**
     * Get stock level for an item at a location
     * @description Retrieve the stock information for a given item at a specific store location.
     */
    get: operations["getStockByLocationAndItem"];
  };
  "/priceintegrity/v1/locations/{locationId}/items/{itemNumber}": {
    /**
     * Get price and location information
     * @description Retrieves pricing, promotion, and location-in-store information for a product.
     */
    get: operations["getPriceAndLocation"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Product: {
      itemNumber?: string;
      itemDescription?: string;
      tillDescription?: string;
      customerFriendlyDescription?: string;
      status?: string;
      temperatureRegime?: string;
      standardUnitOfMeasure?: string;
      manuallyStoreOrderedItem?: string;
      uepItem?: boolean;
      storage?: string[];
      dimensions?: {
        weight?: number;
        length?: number;
        height?: number;
        width?: number;
      };
      productFlags?: {
        perishableInd?: boolean;
        orderableInd?: boolean;
        inventoryInd?: boolean;
        sellableInd?: boolean;
        merchandiseInd?: boolean;
        packInd?: boolean;
        simplePackInd?: boolean;
        constDimenInd?: boolean;
        packType?: string | null;
        catchWeightUom?: string | null;
      };
      packComponents?: ({
          itemNumber?: number;
        })[];
      packs?: ({
          packNumber?: string;
          packQuantity?: number;
      })[];
      commercialHierarchy?: {
        division?: number;
        divisionName?: string;
        group?: number;
        groupName?: string;
        department?: number;
        departmentName?: string;
        class_?: number;
        className?: string;
        subclass?: number;
        subclassName?: string;
      };
      productLife?: {
          productLifeAtTimeOfManufacture?: string;
          minimumAcceptableProductLifedays?: string;
          minimumCPCAcceptanceLife?: number;
          minimumCFCAcceptanceLife?: number;
      };
      imageUrl?: ({
          url?: string;
          shotType?: string | null;
          height?: number | null;
          width?: number | null;
        })[];
      ingredients?: string[];
      allergenInfo?: {
        name: string;
        value: string;
      }[];
      nutritionalInfo?: {
        name: string;
        perComp: string | null;
        perServing?: string | null;
      }[];
      nutritionalHeading?: string;
      productRestrictions?: {
        operatorAgeCheck?: string;
        refundable?: string;
        allowQuantityMultiplier?: string;
        fuelCardRestrictions?: string;
        wetStock?: string;
      };
      brand?: string;
      countryOfOrigin?: string | null;
      productMarketing?: string | null;
      beersWinesSpirits?: {
        alcoholByVolume?: string | null;
        tastingNotes?: string | null;
        additionalTastingNote?: string | null;
        volumeInLitres?: string | null;
        strengthNumberAndWord?: string | null;
      };
      gtins?: {
          id: string;
          type: string;
          additionalProperties?: {
            isPrimaryBarcode?: boolean;
          }
      }[];
      legacyItemNumbers?: string[];
    };
    StockPayload: {
      stockPosition?: ({
          /** @example 10 */
          qty?: number;
          /** @example "each" */
          unitofMeasure?: string;
        })[];
    };
    Location: {
      /** @example "14" */
      aisle?: string;
      /** @example "R02" */
      bayNumber?: string;
      /** @example "3" */
      shelfNumber?: string;
      /** @example 123456 */
      storeWalkSequence?: number;
    };
    PriceIntegrity: {
      product?: {
          itemNumber?: string;
          customerFriendlyDescription?: string;
      },
      space?: {
        standardSpace?: {
          locations?: components["schemas"]["Location"][];
        };
        promotionalSpace?: {
          locations?: components["schemas"]["Location"][];
        };
      };
      prices?: ({
          regularPrice?: number;
        })[];
      promotions?: ({
          marketingAttributes?: {
            offerValue?: string;
          };
        })[];
    };
    Error: {
      /** @example 404 */
      code: number;
      /** @example "Product not found" */
      message: string;
    };
  };
  responses: never;
  parameters: {
    /** @description The unique identifier for the product (SKU). */
    ItemNumber: string;
    /** @description The unique identifier for the store location. */
    LocationId: string;
    /** @description Your API key. */
    ApiKey: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get product details by item number
   * @description Retrieve detailed information about a specific product.
   */
  getProductByItemNumber: {
    parameters: {
      query: {
        apikey: components["parameters"]["ApiKey"];
      };
      path: {
        itemNumber: components["parameters"]["ItemNumber"];
      };
    };
    responses: {
      /** @description Successful response with product details. */
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      /** @description Product not found. */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Get stock level for an item at a location
   * @description Retrieve the stock information for a given item at a specific store location.
   */
  getStockByLocationAndItem: {
    parameters: {
      query: {
        apikey: components["parameters"]["ApiKey"];
      };
      path: {
        locationId: components["parameters"]["LocationId"];
        itemNumber: components["parameters"]["ItemNumber"];
      };
    };
    responses: {
      /** @description Successful response with stock information. */
      200: {
        content: {
          "application/json": components["schemas"]["StockPayload"];
        };
      };
      /** @description Item not found at this location. */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Get price and location information
   * @description Retrieves pricing, promotion, and location-in-store information for a product.
   */
  getPriceAndLocation: {
    parameters: {
      query: {
        apikey: components["parameters"]["ApiKey"];
      };
      path: {
        locationId: components["parameters"]["LocationId"];
        itemNumber: components["parameters"]["ItemNumber"];
      };
    };
    responses: {
      /** @description Successful response with price, promotion, and location details. */
      200: {
        content: {
          "application/json": components["schemas"]["PriceIntegrity"];
        };
      };
      /** @description Item not found at this location. */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}

// Manually added type for Stock Order API
export interface StockOrder {
    orders?: (Order)[] | null;
}
export interface Order {
    orderId: string;
    orderType: string;
    customerOrderId: string;
    customerId: string;
    statusCurrent: string;
    shipToLocationId: number;
    shipFromLocationId: string;
    lines: Lines;
    createdAt: string;
    orderPosition: string;
    delivery?: Delivery;
}
export interface Lines {
    itemLineId: number;
    itemId: string;
    quantityUnitId: string;
    quantityType: string;
    packSize?: number | null;
    status?: (StatusEntity)[] | null;
    delivery?: Delivery;
}
export interface StatusEntity {
    ordered: Ordered;
    receipted?: Receipted;
}
export interface Ordered {
    quantity: number;
    quantityUnit: string;
    quantityType: string;
    packSize?: number | null;
    date: string;
}
export interface Receipted {
    quantity: number;
    quantityUnit: string;
    quantityType: string;
    packSize: number;
    date: string;
}
export interface Delivery {
    dateAvailabilityExpected: string;
    dateDeliveryExpected: string;
}


// Manually added type for Space API
export interface SpaceInfo {
    storeNumber: string;
    min: string;
    variants: any[];
    totalFillQty: number;
    startOfDayQty: number;
    endOfDayQty: number;
    status: string;
    standardSpace: {
        dateFrom: string;
        dateTo: string;
        totalFillQty: number;
        startOfDayQty: number;
        endOfDayQty: number;
        locations: SpaceLocation[];
    };
}

export interface SpaceLocation {
    planClass: number;
    planType: string;
    planName: string;
    gondola: string;
    aisle: string;
    side: string;
    bayNumber: string;
    shelfNumber: string;
    position: string;
    merchandiseType: string;
    unitsWide: number;
    unitsHigh: number;
    unitsDeep: number;
    fillQty: number;
    facings: number;
    dateFrom: string;
    storeWalkSequence: number;
    planBaySequence: string;
    selBlockwidth: number;
    locationCount: number;
    itemOnPeg: string;
}

    