/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/product/v1/items/{itemNumber}": {
    /**
     * Get product details by item number
     * @description Retrieve detailed information about a specific product.
     */
    get: operations["getProductByItemNumber"];
  };
  "/stock/v2/locations/{locationId}/items/{itemNumber}": {
    /**
     * Get stock level for an item at a location
     * @description Retrieve the stock information for a given item at a specific store location.
     */
    get: operations["getStockByLocationAndItem"];
  };
  "/priceintegrity/v1/locations/{locationId}/items/{itemNumber}": {
    /**
     * Get price and location information
     * @description Retrieves pricing, promotion, and location-in-store information for a product.
     */
    get: operations["getPriceAndLocation"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Product: {
      itemNumber?: string;
      itemDescription?: string;
      tillDescription?: string;
      status?: string;
      temperatureRegime?: string;
      dimensions?: {
        weight?: number;
      };
      productFlags?: {
        perishableInd?: boolean;
      };
      packComponents?: ({
          itemNumber?: number;
        })[];
    };
    StockPayload: {
      stockPosition?: ({
          /** @example 10 */
          qty?: number;
          /** @example "each" */
          unitofMeasure?: string;
        })[];
    };
    Location: {
      /** @example "14" */
      aisle?: string;
      /** @example "R02" */
      bayNumber?: string;
      /** @example "3" */
      shelfNumber?: string;
      /** @example 123456 */
      storeWalkSequence?: number;
    };
    PriceIntegrity: {
      space?: {
        standardSpace?: {
          locations?: components["schemas"]["Location"][];
        };
        promotionalSpace?: {
          locations?: components["schemas"]["Location"][];
        };
      };
      prices?: ({
          regularPrice?: number;
        })[];
      promotions?: ({
          marketingAttributes?: {
            offerValue?: string;
          };
        })[];
    };
    Error: {
      /** @example 404 */
      code: number;
      /** @example "Product not found" */
      message: string;
    };
  };
  responses: never;
  parameters: {
    /** @description The unique identifier for the product (SKU). */
    ItemNumber: string;
    /** @description The unique identifier for the store location. */
    LocationId: string;
    /** @description Your API key. */
    ApiKey: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get product details by item number
   * @description Retrieve detailed information about a specific product.
   */
  getProductByItemNumber: {
    parameters: {
      query: {
        apikey: components["parameters"]["ApiKey"];
      };
      path: {
        itemNumber: components["parameters"]["ItemNumber"];
      };
    };
    responses: {
      /** @description Successful response with product details. */
      200: {
        content: {
          "application/json": components["schemas"]["Product"];
        };
      };
      /** @description Product not found. */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Get stock level for an item at a location
   * @description Retrieve the stock information for a given item at a specific store location.
   */
  getStockByLocationAndItem: {
    parameters: {
      query: {
        apikey: components["parameters"]["ApiKey"];
      };
      path: {
        locationId: components["parameters"]["LocationId"];
        itemNumber: components["parameters"]["ItemNumber"];
      };
    };
    responses: {
      /** @description Successful response with stock information. */
      200: {
        content: {
          "application/json": components["schemas"]["StockPayload"];
        };
      };
      /** @description Item not found at this location. */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  /**
   * Get price and location information
   * @description Retrieves pricing, promotion, and location-in-store information for a product.
   */
  getPriceAndLocation: {
    parameters: {
      query: {
        apikey: components["parameters"]["ApiKey"];
      };
      path: {
        locationId: components["parameters"]["LocationId"];
        itemNumber: components["parameters"]["ItemNumber"];
      };
    };
    responses: {
      /** @description Successful response with price, promotion, and location details. */
      200: {
        content: {
          "application/json": components["schemas"]["PriceIntegrity"];
        };
      };
      /** @description Item not found at this location. */
      404: {
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
